name 'automate_compliance'
maintainer 'SSJ Labs'
maintainer_email 'sjha@progress.com'
license 'Apache-2.0'
description 'Enables Chef Automate-managed compliance scanning on nodes'
version '0.1.0'
chef_version '>= 16.0'
supports 'ubuntu', '>= 20.04'
supports 'centos', '>= 7.0'
supports 'redhat', '>= 7.0'
