name 'base_cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures base_cookbook - sets up data_collector and audit compliance'
version '0.1.0'
chef_version '>= 16.0'
supports 'ubuntu'
supports 'debian'
supports 'centos'
supports 'redhat'
supports 'amazon'
supports 'windows'
